### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by sholtomaud** [BuildingXwithJS/node-worker-factorial#1]
I really liked the demo, thank you. Personally I'm not sure what's going on with Promises. People say they are standard, but then there are many different ways of implementing them. 

For example, one Gitter chatter said of your use of Promises:

> new Promise(async (parentResolve, parentReject) => {
> async returns a promise, which is then made into a promise. So right off the bat it's strange. Then an > array of promises is created and waited for using Promise.all(). await is being used here, inside a try/catch.

> All they needed to do was return Promise.all() and it would resolve when it's done everything.
> Looks convoluted and strange, short answer "No it's not proper use of promises"
> Same code again without the try/catch, without the parent promise. Something like:

```javaScript
const calculateFactorialWithWorker = number => {
  // Insert the array preparation code.

  return Promise.all(promises).then(results => {
    return results.reduce((acc, val) => acc * val, 1n);
  });
};
```

Would you be able to refactor your code to be more standard in the use of Promises?

**Comment by yamalight** [comment]
@shotlom that's probably a better way of using promises here, you are right. there's also more than one bit of code that could be made a lot better by some refactoring.
since I'm doing all of the coding live (and try to do it fast) - I tend to do a lot of not very smart decisions. 🤔
but using promises in "canonical" way was not the goal of this project, it was to show how to use workers in node. 
I don't think I have enough time for additional refactoring, but I would be more than happy to accept PR that refactors the code though 😄

**Comment by yamalight** [comment]
Closing this since PR was merged. Feel free to re-open (or create new issues) if needed.
